input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["audit-log"]
    group_id => "logstash-audit-consumer"
    codec => "json"
    auto_offset_reset => "earliest"
  }
}

filter {
  mutate {
    add_field => { "[@metadata][target_index]" => "audit-log-%{+YYYY.MM.dd}" }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "%{[@metadata][target_index]}"
  }
}
