global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: auth-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["auth-service:8081"]

  - job_name: event-management-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["event-management-service:8082"]

  - job_name: seat-inventory-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["seat-inventory-service:8083"]

  - job_name: booking-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["booking-service:8084"]

  - job_name: payment-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["payment-service:8085"]

  - job_name: notification-service
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ["notification-service:8086"]
